name: Perform Build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js 22.x
      uses: actions/setup-node@v5
      with:
        node-version: 22.x
        cache: 'npm'
    - id: Install
      run: npm ci
    - id: Lint
      run: npm run lint
    - id: Build
      run: npm run build
    - id: Test
      run: npm run test