name: Create release

on:
  push:
    branches: [master]

jobs:
  get-package-vesion:
    name: Get package version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get version from package.json
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
  generate-changelog:
    name: Generate changelog
    needs: get-package-vesion
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          args: "-v --tag v${{ env.PACKAGE_VERSION }}"
        env:
          OUTPUT: CHANGELOG.md

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: generate-changelog
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get version from package.json
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ env.PACKAGE_VERSION }}"
          name: "Release v${{ env.PACKAGE_VERSION }}"
          body: "${{ needs.generate-changelog.outputs.release_body }}"

  publish-to-npm:
    name: Publish to registry
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm test
      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
